build:
  version: "2.0"

cards:
  message: "Welcome to Maltese cards related QA APIs "
  contactDetails:
    name: "Jason X - QA Lead"
    email: "xjason91@yahoo.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267