build:
  version: "3.0"

cards:
  message: "Welcome to maltese cards related local APIs "
  contactDetails:
    name: "Jason X - Developer"
    email: "xjason91@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932