build:
  version: "3.0"

loans:
  message: "Welcome to Maltese loans related local APIs "
  contactDetails:
    name: "Jason X - Developer"
    email: "xjason91@yahoo.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934